// Generated by scripts/generate-extension-key.mjs. Do not edit by hand.
// The private key lives outside the repo at ~/.pickfix-signing/pickfix-extension.pem.

/** The value of the extension manifest's `key`: base64 DER SubjectPublicKeyInfo. */
export const EXTENSION_PUBLIC_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtFdoQBVejibsTdPb6470msjSbfoAKbXqtJ/qV1whud5VUz5u81nbkALSDPTCsxNvkJPQN3ufu0mhfDdDJugKKBLr2Zh6QEGTNVasmRu/0O5eupG0i64aJruytU1gtb6bNln0Vjq+cgl6SfB/6PQ95UNG63zgoxhp3/ujFrnlDGoZoKeku2sf1thYJj1v+U2yslbIET06NUkC24PgW4nH5MSWa1X8FEFu1QCIwceGqgYEaRnQxvBjI3CLA5OSNsvSvTYYQv/SL3P5+SvCXXktHsyUABKZr3NQj7Z4NMqaAP+14gcUyq3fh+/RitX+Qk6qkKlaWHWJhL8jUZVrMvfOQwIDAQAB';

/** The Chrome extension id derived from EXTENSION_PUBLIC_KEY. */
export const EXTENSION_ID = 'jmidlcapmahdjjohfaiihlemmjhpeheg';
